# public/admin/config.yml
backend:
    name: git-gateway
    branch: main # The branch to update
    repo: kengitahi/odd-hobby-hub

local_backend: true # set to true to allow decap cms to save file locally during development

media_folder: 'public/uploads' # Folder to store media
public_folder: '/uploads' # Public URL for media

collections:
    - name: 'posts' # Name of the collection
      label: 'Posts' # Label for the admin UI
      folder: 'public/content/posts' # Folder where posts are stored
      create: true # Allow new posts to be created
      slug: '{{slug}}' # Post slug format
      fields: # The fields for each document, usually in front matter
          - {
                name: 'layout',
                label: 'Layout',
                widget: 'hidden',
                default: 'posts',
            }
          - { name: 'title', label: 'Title', widget: 'string' }
          - {
                label: 'Author',
                name: 'author',
                widget: 'string',
                default: 'Hobbies Hub',
            }
          - {
                name: 'date',
                label: 'Publishing Date',
                widget: 'datetime',
                date_format: 'YYYY-MM-DD',
            }
          - {
                label: 'Featured? (Choose to make featured)',
                name: 'is_featured',
                widget: 'boolean',
                default: false,
            }
          - {
                name: 'featured_img',
                label: 'Featured Image',
                widget: 'image',
                allow_multiple: false,
                choose_url:false,
            }
          - { name: 'body', label: 'Body', widget: 'markdown' }
